<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\bin\Module.targets" />

  <ItemGroup>
    <LicenseFile Include="Gallio License.txt" />
    <LicenseFile Include="ASL - Apache Software Foundation License.txt" />
    
    <File Include="Credits.html" />
    
    <Feature Include="NO_ILMERGE" Condition="'$(SkipILMerge)'=='true'" />
    <Feature Include="DOTNET40" Condition="'$(DotNetFrameworkVersion)'=='4.0'" />
  </ItemGroup>
</Project>
